DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXBsZTJAZXhhbXBsZS5jb20iLCJleHAiOjE3MzEzNTczNzUsInVzZXJJZCI6Mn0.Z-8dQjzZyOPxWCfjxIp2DhhXPf72_d_SP0fIVzsMOTA