PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZXhhbXBsZS5jb20iLCJleHAiOjE3MzEzNTU1MzYsInVzZXJJZCI6Mn0._6iTm99KQUNX8T56CMX8hocY8R59SBpaoP1drzJmu_g

{
    "name": "Test event 2",
    "description": "A test event updated",
    "location": "Test location updated",
    "dateTime": "2025-01-01T15:14:00.000Z"
}